# Generated by Django 5.0.3 on 2024-03-28 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0003_remove_distributor_item_distributor_item'),
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='distributor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='distributor_item', to='distributor.distributor', verbose_name='Дистрибутор'),
            preserve_default=False,
        ),
    ]
