# Generated by Django 5.0.3 on 2024-03-28 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано в: ')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='обновленно в: ')),
                ('delete_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='удалено в: ')),
                ('fullname', models.CharField(max_length=120, verbose_name='Полное имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dist_item', to='item.item', verbose_name='Продукты')),
            ],
            options={
                'verbose_name': 'Дистрибьютер',
                'verbose_name_plural': 'Дистрибьютеры',
            },
        ),
    ]
