# Generated by Django 5.0.3 on 2024-03-28 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0001_initial'),
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributor',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dist_item', to='item.item', verbose_name='Продукты'),
        ),
    ]
