# Generated by Django 5.0.3 on 2024-03-28 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0002_alter_distributor_item'),
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distributor',
            name='item',
        ),
        migrations.AddField(
            model_name='distributor',
            name='item',
            field=models.ManyToManyField(blank=True, null=True, related_name='dist_item', to='item.item', verbose_name='Продукты'),
        ),
    ]
